#!/usr/bin/env zsh
#
# Original work Copyright (c) 2019-2020 Sebastian Gniazdowski
# Modified work Copyright (c) 2022 zdharma-continuum and contributors

# vim: set expandtab filetype=zsh shiftwidth=2 softtabstop=2 tabstop=2:
